apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: testjobservice-vpa
  namespace: test
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: testjobservice
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: testjobservice
        minAllowed:
          cpu: "10m"
          memory: "100Mi"
        maxAllowed:
          cpu: "300m"
          memory: "500Mi"
        controlledResources: ["cpu", "memory"]
