apiVersion: v1
kind: Service
metadata:
  name: interviewservice
  namespace: jobportal
  labels:
    app: interviewservice
spec:
  selector:
    app: interviewservice
  ports:
    - name: interview
      port: 8087
      targetPort: interview
  type: ClusterIP



